id: I35C93D5D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:47:43+00:00'
last_modified: '2022-06-08T16:57:08.890547+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21994
  title: སྔགས་འབུམ་རྡོ་རྗེའི་གོ་ཁྲབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6CDC:
      image_group_id: I1KG22072
      title: ''
      total_pages: 194
      order: 1
      base_file: 6CDC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
