id: P010707
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21994
  title: སྔགས་འབུམ་རྡོ་རྗེའི་གོ་ཁྲབ།
  author: ''
  volumes:
    40bf7eb06ada402ca826b713974db118:
      image_group_id: I1KG22072
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
